
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: openproject
      POSTGRES_PASSWORD: openproject
      POSTGRES_DB: openproject
    volumes:
      - postgres_data:/var/lib/postgresql/data

  openproject:
    image: openproject/openproject:15
    container_name: openproject15
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - OPENPROJECT_SECRET_KEY_BASE=secret
      - OPENPROJECT_HOST__NAME=144.91.64.235    # tudominio.com
      - OPENPROJECT_HTTPS=false
      - OPENPROJECT_DEFAULT__LANGUAGE=es
      - DATABASE_URL=postgres://openproject:openproject@db/openproject
    depends_on:
      - db
    volumes:
      - openproject_data:/var/openproject

  nginx:
    image: nginx:alpine
    container_name: openproject-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - openproject

volumes:
  openproject_data:
  postgres_data:
