
services:
  db:
    image: postgres
    container_name: openproject-db
    environment:
      POSTGRES_USER: openproject
      POSTGRES_PASSWORD: openproject
      POSTGRES_DB: openproject
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web

  openproject:
    image: openproject/openproject:15
    container_name: openproject15
    restart: unless-stopped
    environment:
      - OPENPROJECT_SECRET_KEY_BASE=secret
      - OPENPROJECT_HOST__NAME=mantenimientodesoftware.com
      - OPENPROJECT_HTTPS=true
      - OPENPROJECT_DEFAULT__LANGUAGE=es
      - DATABASE_URL=postgres://openproject:openproject@openproject-db/openproject
      - VIRTUAL_HOST=mantenimientodesoftware.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=mantenimientodesoftware.com
      - LETSENCRYPT_EMAIL=faiverlgr@gmail.com
    depends_on:
      - db
    volumes:
      - openproject_data:/var/openproject
    expose:
      - "8080"
    networks:
      - web

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - web

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web

volumes:
  openproject_data:
  postgres_data:

networks:
  web:
    external: true
